version: "3"
services:
  synapse:
   image: matrixdotorg/synapse:latest
   environment:
     - TZ=IR
     - UID=0
     - GID=0
   restart: always
   volumes:
     - ./synapse-data:/data
   ports:
     - "8001:8008"
   networks:
     - element  
  element-web:
   image: vectorim/element-web
   restart: unless-stopped
   volumes:
     - ./element-web-config/config.json:/app/config.json
   ports:
     - "8002:80"
   networks:
     - element

  synapse-admin:
   image: awesometechnologies/synapse-admin
   restart: unless-stopped
   ports:
     - "8003:80"
   networks:
     - element
