version: "3"
services:
  synapse:
   image: matrixdotorg/synapse:latest
   environment:
     - TZ=IR
     - UID=0
     - GID=0
     - SYNAPSE_SERVER_NAME=${HOSTNAME}
   restart: always
   volumes:
     - ./synapse-data/_data/:/data
   ports:
     - "8001:8008"
   networks:
     - element  
  element-web:
   image: vectorim/element-web
   restart: unless-stopped
   environment:
    - MATRIX_THEMES='light,dark'
   volumes:
     - ./element-web-config/config.json:/app/config.json
   ports:
     - "8002:80"
   networks:
     - element
  coturn:
    build:
      context: ./build/coturn
      network: host
    image: myy/coturn:latest
    restart: always
    volumes:
      - "./coturn/conf/turnserver.conf:/etc/turnserver.conf:ro"
      - "./coturn/data:/srv/coturn"
      # You could use "docker secrets" instead
      # Be sure to edit ./coturn/conf/turnserver.conf afterwards if
      # you use "docker secrets" or change these paths
      - ./ssl/turn.yourdomain.com/fullchain.pem:/etc/ssl/fullchain.pem:ro
      - ./ssl/turn.yourdomain.com/privkey.pem:/etc/ssl/privkey.pem:ro
    network_mode: host
  synapse-admin:
   image: awesometechnologies/synapse-admin
   restart: unless-stopped
   environment:
    - REACT_APP_SERVER=http://synapse:8008
   ports:
     - "8003:80"
   networks:
     - element
networks:
 element:
  name: element